import { Nabvar } from "@/components/app/Nabvar";
import "./globals.css";
import type { Metadata } from "next";
import { AppProvider } from "@/context/appContext";
import { Nabvar_Movil } from "@/components/app/Nabvar_Movil";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      suppressHydrationWarning={true}
      lang="en"
      className="text-slate-800 font-lora"
    >
      <AppProvider>
        <body className="darkBackground">
          <Nabvar_Movil />
          <Nabvar />
          {children}
        </body>
      </AppProvider>
    </html>
  );
}
